stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/house_data.csv
      - params.yaml
    outs:
      - data/processed/processed_data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/processed_data.csv
      - params.yaml
    outs:
      - model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - model.pkl
      - data/processed/processed_data.csv
    metrics:
      - scores.json